export const uiTokens = {
  color: {
    page: 'bg-slate-50',
    surface: 'bg-white',
    surfaceMuted: 'bg-slate-50',
    surfaceSubtle: 'bg-slate-100',
    border: 'border-slate-200',
    borderStrong: 'border-slate-300',
    headingText: 'text-slate-950',
    bodyText: 'text-slate-700',
    mutedText: 'text-slate-500',
    subtleText: 'text-slate-400',
    primary: 'text-blue-700',
    primaryBg: 'bg-blue-700',
    primaryBgHover: 'hover:bg-blue-800',
    primarySurface: 'bg-blue-50',
    primaryBorder: 'border-blue-200',
    danger: 'text-rose-700',
    dangerSurface: 'bg-rose-50',
    dangerBorder: 'border-rose-100',
    warning: 'text-amber-700',
    warningSurface: 'bg-amber-50',
    warningBorder: 'border-amber-100',
    success: 'text-emerald-700',
    successSurface: 'bg-emerald-50',
    successBorder: 'border-emerald-100',
    info: 'text-violet-700',
    infoSurface: 'bg-violet-50',
    infoBorder: 'border-violet-100',
  },
  spacing: {
    page: 'px-5 py-6 lg:px-8',
    section: 'mt-6',
    card: 'p-5',
    cardCompact: 'p-4',
    field: 'gap-1.5',
    tableCell: 'px-3 py-3',
    tableCellRelaxed: 'px-3 py-4',
    stack: 'grid gap-4',
    stackCompact: 'grid gap-3',
    inline: 'gap-2',
  },
  typography: {
    pageTitle: 'text-3xl font-extrabold leading-10 text-slate-950',
    sectionTitle: 'text-base font-bold leading-6 text-slate-950',
    cardTitle: 'text-base font-bold text-slate-950',
    body: 'text-sm leading-6 text-slate-700',
    label: 'text-sm font-medium text-slate-600',
    helper: 'text-xs leading-5 text-slate-500',
    linkText: 'font-semibold text-blue-700 underline underline-offset-2',
    metricValue: 'text-3xl font-extrabold leading-9 text-slate-950',
    tableHeader: 'text-xs font-bold uppercase tracking-wide text-slate-500',
  },
  radius: {
    chip: 'rounded-full',
    panel: 'rounded-lg',
    control: 'rounded-lg',
    compact: 'rounded-md',
    pill: 'rounded-full',
  },
  shadow: {
    panel: 'shadow-sm',
  },
} as const
